#!/bin/sh

userresources=$HOME/.Xresources
usermodmap=$HOME/.Xmodmap
sysresources=/etc/X11/xinit/.Xresources
sysmodmap=/etc/X11/xinit/.Xmodmap

# merge in defaults and keymaps
if [ -f $sysresources ]; then
    xrdb -merge $sysresources
fi
if [ -f $sysmodmap ]; then
    xmodmap $sysmodmap
fi
if [ -f "$userresources" ]; then
    xrdb -merge "$userresources"
fi
if [ -f "$usermodmap" ]; then
    xmodmap "$usermodmap"
fi

# start some nice programs setting by system
if [ -d /etc/X11/xinit/xinitrc.d ] ; then
    for f in /etc/X11/xinit/xinitrc.d/?*.sh ; do
        [ -x "$f" ] && . "$f"
    done
    unset f
fi
# auto start program for user
if [ -d ${HOME}/.config/Xorg/xinit.d ]; then
    for f in ${HOME}/.config/Xorg/xinit.d/?*.sh; do
        [ -x "$f" ] && "$f"
    done
    unset f
fi

[[ -r "$HOME/.profile" ]] && . "$HOME/.profile"
[[ -r "$HOME/.xprofile" ]] && . "$HOME/.xprofile"

# MUST LET wmname AND awesome AT THE LAST
wmname LG3D             # Fix java (GUI appears gray only)
exec awesome &> /tmp/awesome.log
