#!/usr/bin/env bash

CURR_PATH=$(cd `dirname $0`; pwd -P)

userresources=$HOME/.Xresources
usermodmap=$HOME/.Xmodmap
sysresources=/etc/X11/xinit/.Xresources
sysmodmap=/etc/X11/xinit/.Xmodmap

# for NVIDIA card
# specify screen
#xrandr --setprovideroutputsource modesetting NVIDIA-0
#xrandr --auto
#xrandr --dpi 96

# merge in defaults and keymaps
if [ -f $sysresources ]; then
    xrdb -merge $sysresources
fi
if [ -f $sysmodmap ]; then
    xmodmap $sysmodmap
fi
if [ -f "$userresources" ]; then
    xrdb -merge "$userresources"
fi
if [ -f "$usermodmap" ]; then
    xmodmap "$usermodmap"
fi

# start some nice programs setting by system
if [ -d /etc/X11/xinit/xinitrc.d ] ; then
    for f in /etc/X11/xinit/xinitrc.d/?*.sh ; do
        [ -x "$f" ] && . "$f"
    done
    unset f
fi
# auto start program for user
if [ -d ${HOME}/.config/Xorg/xinit.d ]; then
    for f in ${HOME}/.config/Xorg/xinit.d/?*.sh; do
        [ -x "$f" ] && "$f"
    done
    unset f
fi

# environment variables for fcitx input
export GTK_IM_MODULE=fcitx
export QT_IM_MODULE=fcitx
export XMODIFIERS="@im=fcitx"

# MUST LET wmname AND awesome AT THE LAST
wmname LG3D             # Fix java (GUI appears gray only)
exec awesome &> /tmp/awesome.log
