colorscheme desert
"set guifont=ubuntu\ mono\ 12
"下面为了设置airline而采用的powerline的字体
"set guifont=Ubuntu\ Mono\ derivative\ Powerline\ 12
set guifont=monaco\ 9
"set linespace=-4
set linespace=-2
set columns=82
let g:airline_left_sep = ''
let g:airline_right_sep = ''
set cursorline
"gvim光标不闪烁
set guicursor=a:blinkon0

